---
- name: (service) service logstash restarted
  service:
    name: logstash
    state: restarted
  notify: debug yum install logstash
# - name: Debug start nginx
#   debug: 
#     msg: 'The key value is !!'
#   when: debug==true or debug==1
    