---
- name: Template etc/nginx/nginx.conf
  template:
    src: etc/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: vagrant
    group: vagrant
    mode: 0766
    validate: nginx -t -c %s
  # notify: start nginx
