---
- name: "python{{ python_version | default(3.6) | regex_replace('([0-9]+).([0-9]+)', '\\1') }} --version"
  shell: "python{{ python_version | default(3.6) | regex_replace('([0-9]+).([0-9]+)', '\\1') }} --version"
  register: string_python_version

- name: debug string_python_version
  debug: 
    msg: "{{ string_python_version }}"