---

- name: "(shell) pip{{ python_version | default(3.6) | regex_replace('([0-9]+).([0-9]+)', '\\1') }} --version"
  shell: "pip{{ python_version | default(3.6) | regex_replace('([0-9]+).([0-9]+)', '\\1') }} --version"
  register: pip_version_string

- name: debug pip__version_string
  debug: 
    msg: "{{ pip_version_string }}"