---
- name: install nginx
  hosts: nginx
  sudo: yes
  tasks:
    - name: install nginx
      apt: name=nginx update_cache=yes state=latest

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted