---
- name: yum install epel-release
  yum:
    name: epel-release
    state: present
    
- name: yum install python-pip
  yum:
    name: python-pip
    state: present
- name: pip --version
  shell: pip --version
  register: pip_version_string
- name: Debug yum install pip
  debug: 
    msg: "{{ pip_version_string }}"