---
- name: yum install epel-release
  yum:
    name: epel-release
    state: present
    
- name: yum install python-pip
  yum:
    name: python-pip
    state: present
  notify: debug yum install python-pip