# 安裝 MySQL 5.6 預設 無密碼
---
- include_vars: "{{ bra | default('fea') }}.yml"
- import_tasks: yum-install-master_manager.yml
- import_tasks: template-etc_masterha_defualt_cnf..yml
- import_tasks: template-etc_master_app_cnf.yml
- import_tasks: template-etc_master_scripts_master_ip_failover.yml
- import_tasks: lineinfile-root_ssh_authorized_keys.yml