# 安裝 MySQL 5.6 預設 無密碼
---
- include_vars: "{{ bra | default('fea') }}.yml"
- import_tasks: yum-install-master_manager.yml
- import_tasks: template-etc_masterha_defualt_cnf..yml
- import_tasks: template-etc_master_app1_cnf.yml