---
- name: (pip) pip uninstall supervisor
  pip:
    name: supervisor
    state: absent
- name: (pip) pip install supervisor
  pip:
    name: supervisor
    state: present
  notify: debug pip install supervisor