---
- name: "(shell) sudo ndb_mgm -e 'show'"
  shell: "sudo ndb_mgm -e 'show'"
  register: string_ndb_show
  ignore_errors: yes
  delegate_to: "{{ host }}"                # 特殊用法委派，可以达到 MySQL1 的 key 放到 MySQL1,2,3 中
  run_once: true
  loop: "{{ groups[bra ~ '-ndb_mgm'] }}"
  loop_control:
    index_var: index
    loop_var: host
    label: "{{ host }}"
  when: mysql_ha == 'ndb'
- name: (debug) string_ndb_show
  run_once: true
  debug: 
    msg: "{{ string_ndb_show }}"
  when: mysql_ha == 'ndb'
  