- name: "(shell) echo y | ssh-keygen -q -f /root/.ssh/id_rsa -t rsa -N ''"
  shell: "echo y | ssh-keygen -q -f /root/.ssh/id_rsa -t rsa -N ''"
  run_once: true
  delegate_to: "{{ host }}"
  loop: "{{ groups[bra ~ '-masterha'] }}"
  loop_control:
    index_var: index
    loop_var: host
    label: "{{ host }}"
  when: mysql_ha == 'mha'

- name: "(shell) cat /root/.ssh/id_rsa.pub"
  shell: "cat /root/.ssh/id_rsa.pub"
  register: string_id_rsa_pub
  run_once: true
  delegate_to: "{{ host }}"
  loop: "{{ groups[bra ~ '-masterha'] }}"
  loop_control:
    index_var: index
    loop_var: host
    label: "{{ host }}"
  when: mysql_ha == 'mha'
  
- name: (file) touch /root/.ssh/authorized_keys
  file:
    path: "/root/.ssh/authorized_keys"
    owner: root
    group: root
    mode: 0700
    state: touch
  delegate_to: "{{ host }}"
  run_once: true
  loop: "{{ groups[bra ~ '-masterha'] }}"
  loop_control:
    index_var: index
    loop_var: host
    label: "{{ host }}"
  when: mysql_ha == 'mha'
   
- name: "(lineinfile) scp root/.ssh/id_rsa.*.pub  >> /root/.ssh/authorized_keys"
  lineinfile:
    dest: /root/.ssh/authorized_keys
    line: "{{ string_id_rsa_pub.results[0].stdout }}"
    insertbefore: 'EOF'
  delegate_to: "{{ host }}"
  run_once: true
  loop: "{{ groups[bra ~ '-masterha'] }}"
  loop_control:
    index_var: index
    loop_var: host
    label: "{{ host }}"
  when: mysql_ha == 'mha'