## 法一, 在 ansible tower 产生三组 SSH key pairs 依序放入 MYSQL 1, MySQL 2, MySQL 3

- name: "(shell) echo y | ssh-keygen -q -f /home/vagrant/www/landan-cicd_devops-ansible/roles/mysql/files/root/.ssh/id_rsa.* -t rsa -N ''"
  local_action: "shell echo y | ssh-keygen -q -f /home/vagrant/www/landan-cicd_devops-ansible/roles/mysql/files/root/.ssh/id_rsa.{{ groups[bra ~ '-mysql'].index(inventory_hostname) + 1 }} -t rsa -N ''"
  when: mysql_ha == 'mha'
  
# - name: echo * > /root/.ssh/id_rsa.pub
#   shell: "echo {{ lookup('file', '/home/vagrant/www/landan-cicd_devops-ansible/roles/mysql/files/root/.ssh/id_rsa.{{ index + 1 }}.pub') }} > /root/.ssh/id_rsa.pub"
#   loop: "{{ MYSQL.SERVERS }}"
#   loop_control:
#     index_var: index
#   when: mysql_ha == 'mha'
# 
# - name: echo * > /root/.ssh/id_rsa
#   shell: "echo '{{ lookup('file', '/home/vagrant/www/landan-cicd_devops-ansible/roles/mysql/files/root/.ssh/id_rsa.{{ index + 1 }}') }}' > /root/.ssh/id_rsa"
#   loop: "{{ MYSQL.SERVERS }}"
#   loop_control:
#     index_var: index
#   when: mysql_ha == 'mha'
# 
# - name: echo '' > /root/.ssh/authorized_keys
#   shell: "echo '' > /root/.ssh/authorized_keys"
#   when: mysql_ha == 'mha'
  
# - name: echo * >> /root/.ssh/authorized_keys
#   shell: "echo {{ lookup('file', '/home/vagrant/www/landan-cicd_devops-ansible/roles/mysql/files/root/.ssh/id_rsa.{{ groups[bra ~ '-mysql'].index(inventory_hostname) + 1 }}.pub') }} >> /root/.ssh/authorized_keys"
#   when: mysql_ha == 'mha'

- name: "(copy) scp root/.ssh/id_rsa.{{ groups[bra ~ '-mysql'].index(inventory_hostname) + 1 }}.pub /root/.ssh/id_rsa.pub"
  copy:
    src: root/.ssh/id_rsa.{{ groups[bra ~ '-mysql'].index(inventory_hostname) + 1 }}.pub
    dest: /root/.ssh/id_rsa.pub
    owner: root
    group: root
    mode: 0700
  when: mysql_ha == 'mha'
      
- name: "(copy) scp root/.ssh/id_rsa.{{ groups[bra ~ '-mysql'].index(inventory_hostname) + 1 }} /root/.ssh/id_rsa"
  copy:
    src: root/.ssh/id_rsa.{{ groups[bra ~ '-mysql'].index(inventory_hostname) + 1 }}
    dest: /root/.ssh/id_rsa
    owner: root
    group: root
    mode: 0700
  when: mysql_ha == 'mha'

- name: (file) rm /root/.ssh/authorized_keys
  file:
    path: "/root/.ssh/authorized_keys"
    owner: root
    group: root
    mode: 0700
    state: absent
  when: mysql_ha == 'mha'

- name: (file) touch /root/.ssh/authorized_keys
  file:
    path: "/root/.ssh/authorized_keys"
    owner: root
    group: root
    mode: 0700
    state: touch
  when: mysql_ha == 'mha'

- name: "(copy) scp root/.ssh/id_rsa.*.pub /root/.ssh/authorized_keys"
  lineinfile:
    dest: /root/.ssh/authorized_keys
    line: "{{ lookup('file', '/home/vagrant/www/landan-cicd_devops-ansible/roles/mysql/files/root/.ssh/id_rsa.{{ index + 1 }}.pub') }}"
    insertbefore: 'EOF'
  loop: "{{ MYSQL.SERVERS }}"
  loop_control:
    index_var: index
    label: "{{ item.HOST }}"
  when: mysql_ha == 'mha'