# 安裝 MySQL 5.6 預設 無密碼
---
- include_vars: "{{ bra | default('fea') }}.yml"


- import_tasks: shell-mysqldump.yml
- import_tasks: yum-install-yum_utils.yml
- import_tasks: yum-install-mysql_comunnity_server.yml
- import_tasks: service-mysqld-restarted.yml # when service mysqld start at the first time, should not template /etc/my.cnf
- import_tasks: template-etc_my_cnf-before_grant.yml
- import_tasks: service-mysqld-restarted.yml
- import_tasks: shell-mysql-tmp_update_user_sql.yml
- import_tasks: service-mysqld-restarted.yml
- import_tasks: template-etc_my_cnf.yml # 之後的 MySQL 才會寫 BINLOG 
- import_tasks: service-mysqld-restarted.yml
- import_tasks: shell-mysql-tmp_grant_sql.yml
- import_tasks: shell-mysql-tmp_alter_user_sql.yml
- import_tasks: shell-mysql-tmp_create_sql.yml
- import_tasks: shell-mysql-tmp_landan_sql.yml
- import_tasks: shell-mysql-tmp_cms_sql.yml
- import_tasks: shell-mysql-tmp_change_master_sql.yml
- import_tasks: lineinfile-root_ssh_authorized_keys.yml


## MYSQL MMM HA 节点部分
- import_tasks: template-etc_hosts.yml
- import_tasks: yum-install-mysql_mmm.yml
- import_tasks: template-etc_mysql_mmm_mmm_common_conf.yml
- import_tasks: template-etc_mysql_mmm_mmm_agent_conf.yml
- import_tasks: service-mysql_mmm_agent-restarted.yml

## MYSQL MMM HA monitor 部分
- import_tasks: template-delegate_to-etc_hosts.yml
- import_tasks: yum-install-delegate_to-mysql_mmm.yml
- import_tasks: template-delegate_to-etc_mysql_mmm_mmm_common_conf.yml
- import_tasks: template-delegate_to-etc_mysql_mmm_mmm_mon_conf.yml
- import_tasks: service-delegate_to-mysql_mmm_monitor-restarted.yml

## MYSQL MHA HA 节点部分
- import_tasks: yum-install-master_node.yml

## MYSQL MHA HA MASTERHA 部分
- import_tasks: yum-install-delegate_to-master_manager.yml
- import_tasks: template-delegate_to-etc_masterha_defualt_cnf.yml
- import_tasks: template-delegate_to-etc_master_app_cnf.yml
- import_tasks: template-delegate_to-etc_master_scripts_master_ip_failover.yml
- import_tasks: template-delegate_to-etc_master_scripts_master_ip_online_change.yml
- import_tasks: file-delegate_to-mkdir-var_log_masterha.yml
- import_tasks: lineinfile-delegate_to-root_ssh_authorized_keys.yml
- import_tasks: shell-delegate_to-masterha_manager.yml
