---
# - name: command mysql_upgrade --force -uroot
#   command: mysql_upgrade --force -u root
- name: template-tmp_alter_user_sql
  template:
    src: tmp/alter_user.sql.j2
    dest: /tmp/alter_user.sql
    owner: vagrant
    group: vagrant
    mode: 0755
- name: "shell mysql --user={{ CONNECTIONS[0]['USER'] }} --password={{ CONNECTIONS[0]['PASSWORD'] }} --force < /tmp/alter_user.sql"
  shell: "mysql --user={{ CONNECTIONS[0]['USER'] }} --password={{ CONNECTIONS[0]['PASSWORD'] }} --force < /tmp/alter_user.sql"
