---
# - name: command mysql_upgrade --force -uroot
#   command: mysql_upgrade --force -u root
- name: (template) scp tmp/grant.sql.j2 /tmp/grant.sql
  template:
    src: tmp/grant.sql.j2
    dest: /tmp/grant.sql
    owner: vagrant
    group: vagrant
    mode: 0755
# - name: "(shell) mysql --user={{ CONNECTIONS[0]['USER'] }} --password={{ CONNECTIONS[0]['PASSWORD'] }} --force < /tmp/grant.sql"
#   shell: "mysql --user={{ CONNECTIONS[0]['USER'] }} --password={{ CONNECTIONS[0]['PASSWORD'] }} --force < /tmp/grant.sql"
