---
- name: shell mysqldump > /tmp/*.sql
  shell: "mysqldump --defaults-extra-file=/etc/my.cnf > /tmp/{{ ansible_date_time.year }}-{{ ansible_date_time.month }}{{ ansible_date_time.day }}-{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}.sql"
  ignore_errors: True # Because this shell will not response, that ansible will determine it as error