---
# - name: command mysql_upgrade --force -uroot
#   command: mysql_upgrade --force -u root
- name: template-tmp_grant_sql
  template:
    src: tmp/grant.sql.j2
    dest: /tmp/grant.sql
    owner: vagrant
    group: vagrant
    mode: 0755
- name: shell mysql < /tmp/grant.sql
  shell: mysql --force < /tmp/grant.sql
