- name: "(template) scp etc/mgm.ini.j2 /etc/mgm.ini"
  template:
    src: etc/mgm.ini.j2
    dest: /etc/mgm.ini
    owner: root
    group: root
    mode: 0755
  delegate_to: "{{ host }}"                # 特殊用法委派，可以达到 MySQL1 的 key 放到 MySQL1,2,3 中
  run_once: true
  loop: "{{ groups[bra ~ '-ndb_mgm'] }}"
  loop_control:
    index_var: index
    loop_var: host
    label: "{{ host }}"
  when: mysql_ha == 'ndb'