- name: "(template) scp etc/masterha_default.cnf.j2 /etc/masterha_default.cnf"
  template:
    src: etc/masterha_default.cnf.j2
    dest: /etc/masterha_default.cnf
    owner: root
    group: root
    mode: 0755
  delegate_to: "{{ host }}"                # 特殊用法委派，可以达到 MySQL1 的 key 放到 MySQL1,2,3 中
  run_once: true
  loop: "{{ groups[bra ~ '-masterha'] }}"
  loop_control:
    index_var: index
    loop_var: host
    label: "{{ host }}"
  when: mysql_ha == 'mha'