---
- name: node -v
  shell: node -v
  register: string_node_version
  become: False
- name: debug string_node_version
  debug: 
    msg: "{{ string_node_version }}"
- name: npm -v
  shell: npm -v
  register: string_npm_version
  become: False
- name: debug string_npm_version
  debug: 
    msg: "{{ string_npm_version }}"