---
- name: (yum) yum install epel-release
  yum:
    name: epel-release
    state: present
    
- name: (yum) yum install java
  yum:
    name: java
    state: present
- name: (shell) java -version
  shell: java -version
  register: java_version_string
- name: (debug) java_version_string
  debug: 
    msg: "{{ java_version_string }}"