---
- name: yum remove nodejs
  yum: 
    name:
      - nodejs
    state: absent
- name: yum install nodejs
  yum: 
    name:
      - nodejs
    state: latest
- name: "npm install n -g"
  command: "npm install n -g"
- name: "command n {{ node_version }}"
  command: "n {{ node_version }}"
- name: node -v
  shell: node -v
  register: node_version_string
  become: False
- name: debug yum install nodejs
  debug: 
    msg: "{{ node_version_string }}"
- name: npm -v
  shell: npm -v
  register: npm_version_string
  become: False
- name: debug yum install npm
  debug: 
    msg: "{{ npm_version_string }}"