---
- name: (template) scp etc/elasticsearch/logging.yml.j2 /etc/elasticsearch/logging.yml
  template:
    src: etc/elasticsearch/logging.yml.j2
    dest: /etc/elasticsearch/logging.yml
    owner: vagrant
    group: vagrant
    mode: 0766
