---
mysql_version: 5.6
mysql_ha: 'master-slave' # master-slave,master-master-slave , mmm, cluster, mha, mmm-cluster
MYSQL:
  GTID: yes
  HOSTS:
    - IP: '10.0.0.81' # MASTER
      CONNECTIONS:
        - drop_user: false                  # 第一个 CONNECTIONS 为 root@localhost 使用 ， 请勿改变次序
          with_grant_option: true
          GRANTS:
            - 'ALL'
          USER: 'root'
          HOST: 'localhost'                 # 提供 Linux shell  连取 127.0.0.1 ，在 localhost
          PASSWORD: 'mysql_pass_cli'
          DATABASE: '*'
        - drop_user: false
          with_grant_option: true
          GRANTS: 
            - 'ALL'
          USER: 'root'
          HOST: '127.0.0.1'                 # 提供 Linux shell  连取 127.0.0.1 ，在 localhost
          PASSWORD: 'mysql_pass_cli'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: true
          GRANTS: 
            - 'ALL'
          USER: 'root'
          HOST: '10.0.2.2'                 # 提供 Windows or Mac 从 办公室 ip (利用 VM NAT    经过 10.0.2.2)  连取 127.0.0.1 ，在 VM 外网
          PASSWORD: 'mysql_pass_natgateway'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: true
          GRANTS: 
            - 'ALL'
          USER: 'root'
          HOST: '10.0.0.1'                 # 提供 Windows or Mac 从 办公室 ip (利用 VM ROUTER 经过 10.0.0.1)  连取 10.0.0.21 ，在 VM 外网
          PASSWORD: 'mysql_pass_router'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: false
          GRANTS: 
            - 'SELECT'
            - 'INSERT'
            - 'UPDATE'
            - 'CREATE'
            - 'CREATE TEMPORARY TABLES'
            - 'LOCK TABLES'
            - 'EXECUTE'
            - 'CREATE ROUTINE'
            - 'ALTER ROUTINE'
          USER: 'backend'
          HOST: '127.0.0.1'                # 提供 PHP GOLANG NODEJS 从 127.0.0.1 连取 127.0.0.1 ，在 VN localhost
          PASSWORD: 'mysql_pass_backend'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: false
          GRANTS:
            - 'SELECT'
            - 'INSERT'
            - 'UPDATE'
            - 'CREATE'
            - 'CREATE TEMPORARY TABLES'
            - 'LOCK TABLES'
            - 'EXECUTE'
            - 'CREATE ROUTINE'
            - 'ALTER ROUTINE'
          USER: 'backend'
          HOST: 'localhost'                # 提供 PHP GOLANG NODEJS 从 localhost 连取 localhost ，在 VN localhost
          PASSWORD: 'mysql_pass_backend'
          DATABASE: '*' 
        - drop_user: true
          with_grant_option: false
          GRANTS:
            - 'SELECT'
            - 'INSERT'
            - 'UPDATE'
            - 'CREATE'
            - 'CREATE TEMPORARY TABLES'
            - 'LOCK TABLES'
            - 'EXECUTE'
            - 'CREATE ROUTINE'
            - 'ALTER ROUTINE'
          USER: 'backend'
          HOST: '10.0.0.41'                # 提供 GOLANG 从 10.0.0.* 连取 10.0.0.81 ，在 VM 内网
          PASSWORD: 'mysql_pass_backend'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: false
          GRANTS:
            - 'SELECT'
            - 'INSERT'
            - 'UPDATE'
            - 'CREATE'
            - 'CREATE TEMPORARY TABLES'
            - 'LOCK TABLES'
            - 'EXECUTE'
            - 'CREATE ROUTINE'
            - 'ALTER ROUTINE'
          USER: 'backend'
          HOST: '10.0.0.42'                # 提供 GOLANG  从 10.0.0.* 连取 10.0.0.81 ，在 VM 内网
          PASSWORD: 'mysql_pass_backend'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: false
          GRANTS:
            - 'SELECT'
            - 'INSERT'
            - 'UPDATE'
            - 'CREATE'
            - 'CREATE TEMPORARY TABLES'
            - 'LOCK TABLES'
            - 'EXECUTE'
            - 'CREATE ROUTINE'
            - 'ALTER ROUTINE'
          USER: 'backend'
          HOST: '10.0.0.51'                # 提供 PHP  从 10.0.0.* 连取 10.0.0.81 ，在 VM 内网
          PASSWORD: 'mysql_pass_backend'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: false
          GRANTS:
            - 'SELECT'
            - 'INSERT'
            - 'UPDATE'
            - 'CREATE'
            - 'CREATE TEMPORARY TABLES'
            - 'LOCK TABLES'
            - 'EXECUTE'
            - 'CREATE ROUTINE'
            - 'ALTER ROUTINE'
          USER: 'backend'
          HOST: '10.0.0.52'                # 提供 PHP  从 10.0.0.* 连取 10.0.0.81 ，在 VM 内网
          PASSWORD: 'mysql_pass_backend'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: false
          GRANTS: 
            - 'REPLICATION SLAVE'
            - 'REPLICATION CLIENT'
          USER: 'replicator'
          HOST: '10.0.0.82'                # 提供 MYSQL SLAVE 从 10.0.0.* 连取 10.0.0.81 ，在 VM 内网
          PASSWORD: 'mysql_pass_replicator'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: false
          GRANTS: 
            - 'REPLICATION SLAVE'
            - 'REPLICATION CLIENT'
          USER: 'replicator'
          HOST: '10.0.0.83'                # 提供 MYSQL SLAVE 从 10.0.0.* 连取 10.0.0.81 ，在 VM 内网
          PASSWORD: 'mysql_pass_replicator'
          DATABASE: '*'
    - IP: '10.0.0.82' # SLAVE
      CONNECTIONS:
        - drop_user: false                  # 第一个 CONNECTIONS 为 root@localhost 使用 ， 请勿改变次序
          with_grant_option: true
          GRANTS:
            - 'ALL'
          USER: 'root'
          HOST: 'localhost'                 # 提供 Linux shell  连取 127.0.0.1 ，在 localhost
          PASSWORD: 'mysql_pass_cli'
          DATABASE: '*'
        - drop_user: false
          with_grant_option: true
          GRANTS: 
            - 'ALL'
          USER: 'root'
          HOST: '127.0.0.1'                 # 提供 Linux shell  连取 127.0.0.1 ，在 localhost
          PASSWORD: 'mysql_pass_cli'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: true
          GRANTS: 
            - 'ALL'
          USER: 'root'
          HOST: '10.0.2.2'                 # 提供 Windows or Mac 从 办公室 ip (利用 VM NAT    经过 10.0.2.2)  连取 127.0.0.1 ，在 VM 外网
          PASSWORD: 'mysql_pass_natgateway'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: true
          GRANTS: 
            - 'ALL'
          USER: 'root'
          HOST: '10.0.0.1'                 # 提供 Windows or Mac 从 办公室 ip (利用 VM ROUTER 经过 10.0.0.1)  连取 10.0.0.21 ，在 VM 外网
          PASSWORD: 'mysql_pass_router'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: false
          GRANTS:
            - 'SELECT'
            - 'INSERT'
            - 'UPDATE'
            - 'CREATE'
            - 'CREATE TEMPORARY TABLES'
            - 'LOCK TABLES'
            - 'EXECUTE'
            - 'CREATE ROUTINE'
            - 'ALTER ROUTINE'
          USER: 'backend'
          HOST: '10.0.0.41'                # 提供 GOLANG 从 10.0.0.* 连取 10.0.0.81 ，在 VM 内网
          PASSWORD: 'mysql_pass_backend'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: false
          GRANTS:
            - 'SELECT'
            - 'INSERT'
            - 'UPDATE'
            - 'CREATE'
            - 'CREATE TEMPORARY TABLES'
            - 'LOCK TABLES'
            - 'EXECUTE'
            - 'CREATE ROUTINE'
            - 'ALTER ROUTINE'
          USER: 'backend'
          HOST: '10.0.0.42'                # 提供 GOLANG  从 10.0.0.* 连取 10.0.0.81 ，在 VM 内网
          PASSWORD: 'mysql_pass_backend'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: false
          GRANTS:
            - 'SELECT'
            - 'INSERT'
            - 'UPDATE'
            - 'CREATE'
            - 'CREATE TEMPORARY TABLES'
            - 'LOCK TABLES'
            - 'EXECUTE'
            - 'CREATE ROUTINE'
            - 'ALTER ROUTINE'
          USER: 'backend'
          HOST: '10.0.0.51'                # 提供 PHP  从 10.0.0.* 连取 10.0.0.81 ，在 VM 内网
          PASSWORD: 'mysql_pass_backend'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: false
          GRANTS:
            - 'SELECT'
            - 'INSERT'
            - 'UPDATE'
            - 'CREATE'
            - 'CREATE TEMPORARY TABLES'
            - 'LOCK TABLES'
            - 'EXECUTE'
            - 'CREATE ROUTINE'
            - 'ALTER ROUTINE'
          USER: 'backend'
          HOST: '10.0.0.52'                # 提供 PHP  从 10.0.0.* 连取 10.0.0.81 ，在 VM 内网
          PASSWORD: 'mysql_pass_backend'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: false
          GRANTS: 
            - 'REPLICATION SLAVE'
            - 'REPLICATION CLIENT'
          USER: 'replicator'
          HOST: '10.0.0.83'                # 提供 MYSQL SLAVE 从 10.0.0.* 连取 10.0.0.81 ，在 VM 内网
          PASSWORD: 'mysql_pass_replicator'
          DATABASE: '*'
    - IP: '10.0.0.83' # SLAVE
      CONNECTIONS:
        - drop_user: false                  # 第一个 CONNECTIONS 为 root@localhost 使用 ， 请勿改变次序
          with_grant_option: true
          GRANTS:
            - 'ALL'
          USER: 'root'
          HOST: 'localhost'                 # 提供 Linux shell  连取 127.0.0.1 ，在 localhost
          PASSWORD: 'mysql_pass_cli'
          DATABASE: '*'
        - drop_user: false
          with_grant_option: true
          GRANTS: 
            - 'ALL'
          USER: 'root'
          HOST: '127.0.0.1'                 # 提供 Linux shell  连取 127.0.0.1 ，在 localhost
          PASSWORD: 'mysql_pass_cli'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: true
          GRANTS: 
            - 'ALL'
          USER: 'root'
          HOST: '10.0.2.2'                 # 提供 Windows or Mac 从 办公室 ip (利用 VM NAT    经过 10.0.2.2)  连取 127.0.0.1 ，在 VM 外网
          PASSWORD: 'mysql_pass_natgateway'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: true
          GRANTS: 
            - 'ALL'
          USER: 'root'
          HOST: '10.0.0.1'                 # 提供 Windows or Mac 从 办公室 ip (利用 VM ROUTER 经过 10.0.0.1)  连取 10.0.0.21 ，在 VM 外网
          PASSWORD: 'mysql_pass_router'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: false
          GRANTS:
            - 'SELECT'
            - 'INSERT'
            - 'UPDATE'
            - 'CREATE'
            - 'CREATE TEMPORARY TABLES'
            - 'LOCK TABLES'
            - 'EXECUTE'
            - 'CREATE ROUTINE'
            - 'ALTER ROUTINE'
          USER: 'backend'
          HOST: '10.0.0.41'                # 提供 GOLANG 从 10.0.0.* 连取 10.0.0.81 ，在 VM 内网
          PASSWORD: 'mysql_pass_backend'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: false
          GRANTS:
            - 'SELECT'
            - 'INSERT'
            - 'UPDATE'
            - 'CREATE'
            - 'CREATE TEMPORARY TABLES'
            - 'LOCK TABLES'
            - 'EXECUTE'
            - 'CREATE ROUTINE'
            - 'ALTER ROUTINE'
          USER: 'backend'
          HOST: '10.0.0.42'                # 提供 GOLANG  从 10.0.0.* 连取 10.0.0.81 ，在 VM 内网
          PASSWORD: 'mysql_pass_backend'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: false
          GRANTS:
            - 'SELECT'
            - 'INSERT'
            - 'UPDATE'
            - 'CREATE'
            - 'CREATE TEMPORARY TABLES'
            - 'LOCK TABLES'
            - 'EXECUTE'
            - 'CREATE ROUTINE'
            - 'ALTER ROUTINE'
          USER: 'backend'
          HOST: '10.0.0.51'                # 提供 PHP  从 10.0.0.* 连取 10.0.0.81 ，在 VM 内网
          PASSWORD: 'mysql_pass_backend'
          DATABASE: '*'
        - drop_user: true
          with_grant_option: false
          GRANTS:
            - 'SELECT'
            - 'INSERT'
            - 'UPDATE'
            - 'CREATE'
            - 'CREATE TEMPORARY TABLES'
            - 'LOCK TABLES'
            - 'EXECUTE'
            - 'CREATE ROUTINE'
            - 'ALTER ROUTINE'
          USER: 'backend'
          HOST: '10.0.0.52'                # 提供 PHP  从 10.0.0.* 连取 10.0.0.81 ，在 VM 内网
          PASSWORD: 'mysql_pass_backend'
          DATABASE: '*'

  DATADIR: '/var/lib/mysql'
  BIND_ADDRESS: '0.0.0.0'
  CREATE_DATABASES:
    - landan
    - vpn
    - lorentz
    - chatshier
    - nuoya
    - legeo