---
mysql_version: 5.6
DATADIR: '/var/lib/mysql'
BIND_ADDRESS: '0.0.0.0'
CREATE_DATABASES:
  - landan
  - vpn
  - lorentz
  - chatshier
  - nouya
CONNECTIONS:
  - drop_user: false                  # 第一个 CONNECTIONS 为 root@localhost 使用 ， 请勿改变次序
    with_grant_option: true
    USER: 'root'
    HOST: 'localhost'                 # 提供 Linux shell  连取 127.0.0.1 ，在 localhost
    PASSWORD: 'mysql_pass_localhost'
    DATABASE: '*'
  - drop_user: false
    with_grant_option: true
    USER: 'root'
    HOST: '127.0.0.1'                 # 提供 Linux shell  连取 127.0.0.1 ，在 localhost
    PASSWORD: 'mysql_pass_localhost'
    DATABASE: '*'
  - drop_user: true
    with_grant_option: true
    USER: 'root'
    HOST: '123.176.102.11'                # 提供 PHP GOLANG NODEJS 从 10.0.0.* 连取 10.0.0.21 ，在 VM 内网
    PASSWORD: 'mysql_pass'
    DATABASE: '*'
  - drop_user: true
    with_grant_option: false
    USER: 'backend'
    HOST: '123.176.102.11'                # 提供 PHP GOLANG NODEJS 从 10.0.0.* 连取 10.0.0.21 ，在 VM 内网
    PASSWORD: 'mysql_pass'
    DATABASE: '*'