# 安裝 MySQL 5.6 預設 無密碼
---
- name: Main Task Starts
  import_tasks: yum-install-rpm.yml
- import_tasks: yum-install-yum_utils.yml
- import_tasks: yum-install-php.yml
- import_tasks: template-etc_php_ini.yml
- import_tasks: copy-etc_php_fpm_d_www_conf.yml
- import_tasks: service-php_fpm-restarted.yml