---
- name: (template) scp etc/php.ini.j2 /etc/php.ini
  template:
    src: etc/php.ini.j2
    dest: /etc/php.ini
    owner: vagrant
    group: vagrant
    mode: 0766
    backup: no
       
# - name: (template) scp etc/php.d/xdebug.ini.j2 /etc/php.d/xdebug.ini
#   template:
#     src: etc/php.d/xdebug.ini.j2
#     dest: /etc/php.d/xdebug.ini
#     owner: vagrant
#     group: vagrant
#     mode: 0766
#     backup: 