---
- name: yum insatll epel.rpm
  yum: 
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
- name: yum insatll remi.rpm
  yum: 
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
- name: yum install yum-utils
  yum:
    name: yum-utils
    state: present
- name: 'command yum-config-manager --disable remi-php'
  command: "yum-config-manager --disable {{ item }}"
  with_items:
    - remi-php54
    - remi-php55
    - remi-php56
    - remi-php70
    - remi-php71
    - remi-php72
    - remi-php73
  loop_control:
    label: "yum-config-manager --disable {{ item }}"

- name: "command yum-config-manager --enable remi-php"
  command: "yum-config-manager --enable {{ item }}"
  with_items:
    - "remi-php{{ php_version | default(5.6) | regex_replace('([0-9]+).([0-9]+)', '\\1\\2') }}"

- name: yum remove php...
  yum: 
    name: php*
    state: absent

- name: yum install php...
  yum: 
    name:
      - php
      - php-memcached
      - php-pdo
      - php-pdo_mysql
      - php-mcrypt 
      - php-cli 
      - php-gd 
      - php-curl 
      - php-mysql 
      - php-ldap 
      - php-zip 
      - php-fileinfo
      - php-fpm
      - php-common 
      - php-devel 
      - php-json 
      - php-mbstring 
      - php-mysqlnd 
      - php-xml 
      - php-xmlrpc 
      - php-opcache
      - php-xdebug
      - php-swoole
    state: latest

- name: php -v
  shell: php -v
  register: php_version_string
- name: Debug yum install php...
  debug: 
    msg: "{{ php_version_string }}"