---
- name: 'yum-config-manager --enable remi-php72'
  command: yum-config-manager --enable remi-php72

- name: yum install php...
  yum: 
    name:
      - php 
      - php-mcrypt 
      - php-cli 
      - php-gd 
      - php-curl 
      - php-mysql 
      - php-ldap 
      - php-zip 
      - php-fileinfo
      - php-fpm
      - php-common 
      - php-devel 
      - php-json 
      - php-mbstring 
      - php-mysqlnd 
      - php-xml 
      - php-xmlrpc 
      - php-opcache
    state: latest
- name: php -v
  shell: php -v
  register: php_version_string
- name: Debug yum install php...
  debug: 
    msg: "{{ php_version_string }}"
    