---
- name: Install feature cms-service_admin_backend-scms
  hosts: fea-cms-service_admin_backend-scms
  strategy: linear # free, debug
  gather_facts: true
  become: true
  pre_tasks:
    - shell: echo 'playbook cms-service_admin_backend-scms starts'
  roles:
    - role: cms-service_admin_backend-scms
      vars:
        bra: fea
      when: branch == 'fea' or branch == 'feature' or branch == 'all' or branch is not defined
  post_tasks:
    - shell: echo 'playbook cms-service_admin_backend-scms ends'
