---
- name: Install feature nginx
  hosts: fea_nginx
  become: true
  pre_tasks:
    - shell: echo 'playbook nginx starts'
  roles:
    - role: nginx
      when: branch == 'fea' or branch == 'feature' or branch == 'all'
  post_tasks:
    - shell: echo 'playbook nginx ends'
  vars:
    SERVER_NAME: 'fea.qjj8.com'
- name: Install develop nginx
  hosts: dev_nginx
  become: true
  pre_tasks:
    - shell: echo 'playbook nginx starts'
  roles:
    - role: nginx
      when: branch == 'dev' or branch == 'develop' or branch == 'all'
  post_tasks:
    - shell: echo 'playbook nginx ends'
  vars:
    SERVER_NAME: 'dev.qjj8.com'
# - name: Install release nginx
#   hosts: rel_nginx
#   become: true
#   pre_tasks:
#     - shell: echo 'playbook nginx starts'
#   roles:
#     - role: nginx
#   post_tasks:
#     - shell: echo 'playbook nginx ends'
#   tags:
#     - rel
# - name: Install master nginx
#   hosts: mas_nginx
#   become: true
#   pre_tasks:
#     - shell: echo 'playbook nginx starts'
#   roles:
#     - role: nginx
#   post_tasks:
#     - shell: echo 'playbook nginx ends'
#   tags:
#     - mas