---
- name: Install feature nginx
  hosts: fea_nginx
  become: true

  pre_tasks:
    - shell: echo 'playbook nginx starts'
  roles:
    - role: nginx
  post_tasks:
    - shell: echo 'playbook nginx ends'
  tags:
    - fea
- name: Install develop nginx
  hosts: dev_nginx
  become: true
  pre_tasks:
    - shell: echo 'playbook nginx starts'
  roles:
    - role: nginx
  post_tasks:
    - shell: echo 'playbook nginx ends'
  tags:
    - dev
# - name: Install release nginx
#   hosts: rel_nginx
#   become: true
#   pre_tasks:
#     - shell: echo 'playbook nginx starts'
#   roles:
#     - role: nginx
#   post_tasks:
#     - shell: echo 'playbook nginx ends'
#   tags:
#     - rel
# - name: Install master nginx
#   hosts: mas_nginx
#   become: true
#   pre_tasks:
#     - shell: echo 'playbook nginx starts'
#   roles:
#     - role: nginx
#   post_tasks:
#     - shell: echo 'playbook nginx ends'
#   tags:
#     - mas