---
- name: Install php
  hosts: fea_node
  become: true

  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install php
    yum:
      name:
        - mcrypt
        - php
        - php-curl
        - php-fpm
        - php-intl
        - php-json
        - php-mcrypt
      state: present