---
- name: Install feature redis
  hosts: fea_redis
  strategy: linear # free, debug
  gather_facts: true
  become: true
  pre_tasks:
    - shell: echo 'playbook redis starts'
  roles:
    - role: redis
      vars:
        bra: fea
      when: branch == 'fea' or branch == 'feature' or branch == 'all' or branch is not defined
  post_tasks:
    - shell: echo 'playbook redis ends'
  vars:
- name: Install develop redis
  hosts: dev_redis
  strategy: linear # free, debug
  gather_facts: true
  become: true
  pre_tasks:
    - shell: echo 'playbook redis starts'
  roles:
    - role: redis
      vars:
        bra: dev
      when: branch == 'dev' or branch == 'develop' or branch == 'all'
  post_tasks:
    - shell: echo 'playbook redis ends'
