## 法一, 在 ansible tower 产生三组 SSH key pairs 依序放入 MYSQL 1, MySQL 2, MySQL 3

# - name: "(shell) echo y | ssh-keygen -q -f /home/vagrant/www/landan-cicd_devops-ansible/roles/mysql/files/root/.ssh/id_rsa.* -t rsa -N ''"
#   local_action: "shell echo y | ssh-keygen -q -f /home/vagrant/www/landan-cicd_devops-ansible/roles/mysql/files/root/.ssh/id_rsa.{{ groups[bra ~ '-mysql'].index(inventory_hostname) + 1 }} -t rsa -N ''"
#   when: mysql_ha == 'mha'
# 
# - name: "(copy) scp root/.ssh/id_rsa.{{ groups[bra ~ '-mysql'].index(inventory_hostname) + 1 }}.pub /root/.ssh/id_rsa.pub"
#   copy:
#     src: root/.ssh/id_rsa.{{ groups[bra ~ '-mysql'].index(inventory_hostname) + 1 }}.pub
#     dest: /root/.ssh/id_rsa.pub
#     owner: root
#     group: root
#     mode: 0700
#   when: mysql_ha == 'mha'
#   
# - name: "(copy) scp root/.ssh/id_rsa.{{ groups[bra ~ '-mysql'].index(inventory_hostname) + 1 }} /root/.ssh/id_rsa"
#   copy:
#     src: root/.ssh/id_rsa.{{ groups[bra ~ '-mysql'].index(inventory_hostname) + 1 }}
#     dest: /root/.ssh/id_rsa
#     owner: root
#     group: root
#     mode: 0700
#   when: mysql_ha == 'mha'
# 
# - name: (file) rm /root/.ssh/authorized_keys
#   file:
#     path: "/root/.ssh/authorized_keys"
#     owner: root
#     group: root
#     mode: 0700
#     state: absent
#   when: mysql_ha == 'mha'
# 
# - name: (file) touch /root/.ssh/authorized_keys
#   file:
#     path: "/root/.ssh/authorized_keys"
#     owner: root
#     group: root
#     mode: 0700
#     state: touch
#   when: mysql_ha == 'mha'
# 
# - name: "(copy) scp root/.ssh/id_rsa.*.pub  >> /root/.ssh/authorized_keys"
#   lineinfile:
#     dest: /root/.ssh/authorized_keys
#     line: "{{ lookup('file', '/home/vagrant/www/landan-cicd_devops-ansible/roles/mysql/files/root/.ssh/id_rsa.{{ index + 1 }}.pub') }}"
#     insertbefore: 'EOF'
#   loop: "{{ MYSQL.SERVERS }}"
#   loop_control:
#     index_var: index
#     label: "{{ item.HOST }}"
#   when: mysql_ha == 'mha'
#   
  
## 法二, 在 MYSQL 1, MySQL 2, MySQL 3 各一组 SSH KEY PAIR 再 利用 委派 放到其他 MYSQLs
  
- name: "(shell) echo y | ssh-keygen -q -f /root/.ssh/id_rsa -t rsa -N ''"
  shell: "echo y | ssh-keygen -q -f /root/.ssh/id_rsa -t rsa -N ''"
  when: mysql_ha == 'mha'

- name: "(shell) cat /root/.ssh/id_rsa.pub"
  shell: "cat /root/.ssh/id_rsa.pub"
  register: string_id_rsa_pub
  when: mysql_ha == 'mha'
  
- name: (file) rm /root/.ssh/authorized_keys
  file:
    path: "/root/.ssh/authorized_keys"
    owner: root
    group: root
    mode: 0700
    state: absent
  when: mysql_ha == 'mha'

- name: (file) touch /root/.ssh/authorized_keys
  file:
    path: "/root/.ssh/authorized_keys"
    owner: root
    group: root
    mode: 0700
    state: touch
  when: mysql_ha == 'mha'
  
- name: "(lineinfile) scp root/.ssh/id_rsa.*.pub  >> /root/.ssh/authorized_keys"
  lineinfile:
    dest: /root/.ssh/authorized_keys
    line: "{{ string_id_rsa_pub.stdout }}"
    insertbefore: 'EOF'
  delegate_to: "{{ host }}"                # 特殊用法委派，可以达到 MySQL1 的 key 放到 MySQL1,2,3 中
  loop: "{{ groups[bra ~ '-mysql'] }}"
  loop_control:
    index_var: index
    loop_var: host
    label: "{{ host }}"
  when: mysql_ha == 'mha'