- name: (template) scp etc/mysql-mmm/mmm_mon.conf.j2 /etc/mysql-mmm/mmm_mon.conf
  template:
    src: etc/mysql-mmm/mmm_mon.conf.j2
    dest: /etc/mysql-mmm/mmm_mon.conf
    owner: vagrant
    group: vagrant
    mode: 0640
    backup: no
  delegate_to: "{{ host }}"                # 特殊用法委派，可以达到 MySQL1 的 key 放到 MySQL1,2,3 中
  run_once: true
  loop: "{{ groups[bra ~ '-mmm_monitor'] }}"
  loop_control:
    index_var: index
    loop_var: host
    label: "{{ host }}"
  when: mysql_ha == 'mmm'