# 安裝 MySQL 5.6 預設 無密碼
---
- name: Main Task Starts
  import_tasks: command-rpm-mysql_community.yml
- import_tasks: yum-install-mysql_community_server.yml
- import_tasks: service-mysqld-restarted.yml
- import_tasks: command-mysql-tmp_grant_sql.yml