- name: (template) scp etc/hosts.j2 /etc/hosts
  template:
    src: etc/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0755
    backup: yes
  delegate_to: "{{ host }}"                # 特殊用法委派，可以达到 MySQL1 的 key 放到 MySQL1,2,3 中
  run_once: true
  loop: "{{ groups[bra ~ '-mmm_monitor'] }}"
  loop_control:
    index_var: index
    loop_var: host
    label: "{{ host }}"