---
- name: (yum) yum install http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  yum: #
    name:  http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  delegate_to: "{{ host }}"                # 特殊用法委派，可以达到 MySQL1 的 key 放到 MySQL1,2,3 中
  run_once: true
  loop: "{{ groups[bra ~ '-masterha'] }}"
  loop_control:
    index_var: index
    loop_var: host
    label: "{{ host }}"
  when: mysql_ha == 'mha'
  
- name: "(yum) yum install perl-DBD-MySQL perl-Config-Tiny perl-Log-Dispatch perl-Parallel-ForkManager"
  yum: 
    name:
      - perl-DBD-MySQL
      - perl-Config-Tiny
      - perl-Log-Dispatch 
      - perl-Parallel-ForkManager
    state: latest
  delegate_to: "{{ host }}"                # 特殊用法委派，可以达到 MySQL1 的 key 放到 MySQL1,2,3 中
  run_once: true
  loop: "{{ groups[bra ~ '-masterha'] }}"
  loop_control:
    index_var: index
    loop_var: host
    label: "{{ host }}"
  when: mysql_ha == 'mha'
  
- name: (yum) yum install https://github.com/yoshinorim/mha4mysql-node/releases/download/v0.58/mha4mysql-node-0.58-0.el7.centos.noarch.rpm
  yum: #  https://qiniu.wsfnk.com/mha4mysql-node-0.58-0.el7.centos.noarch.rpm
    name:  https://github.com/yoshinorim/mha4mysql-node/releases/download/v0.58/mha4mysql-node-0.58-0.el7.centos.noarch.rpm
    state: present
  delegate_to: "{{ host }}"                # 特殊用法委派，可以达到 MySQL1 的 key 放到 MySQL1,2,3 中
  run_once: true
  loop: "{{ groups[bra ~ '-masterha'] }}"
  loop_control:
    index_var: index
    loop_var: host
    label: "{{ host }}"
  when: mysql_ha == 'mha'
## mha-manager 也需要安装 mha-node  
- name: (yum) yum install https://github.com/yoshinorim/mha4mysql-manager/releases/download/v0.58/mha4mysql-manager-0.58-0.el7.centos.noarch.rpm
  yum: #  https://qiniu.wsfnk.com/mha4mysql-manager-0.58-0.el7.centos.noarch.rpmsh
    name:  https://github.com/yoshinorim/mha4mysql-manager/releases/download/v0.58/mha4mysql-manager-0.58-0.el7.centos.noarch.rpm
    state: present
  delegate_to: "{{ host }}"                # 特殊用法委派，可以达到 MySQL1 的 key 放到 MySQL1,2,3 中
  run_once: true
  loop: "{{ groups[bra ~ '-masterha'] }}"
  loop_control:
    index_var: index
    loop_var: host
    label: "{{ host }}"
  when: mysql_ha == 'mha'
  
  