---
- name: service beanstalkd restarted
  service:
    name: beanstalkd
    state: restarted
# - name: Debug start nginx
#   debug: 
#     msg: 'The key value is !!'
#   when: debug==true or debug==1
    